### ISSUE TITLE
Is this project accepting pull requests?

### ISSUE THREAD

**Issue by axllent** [enomotodev/gitlabci-composer-update-mr#4]
Hi @enomotodev. Given that this project was last updated over 2 years ago, I'm just wondering if you are accepting any pull requests and still actively developing this project?

There are two main feature changes (and possibly a third) I need to make:
1. Use something other than the variable `GITLAB_API_PRIVATE_TOKEN` as that is too generic. I would fall back to `GITLAB_API_PRIVATE_TOKEN` if the other token name isn't set (for backwards compatibility), but I was thinking of maybe `COMPOSER_UPDATE_MR_PRIVATE_TOKEN` or something a bit more descriptive.
2. PHP 8 support, newer guzzle etc. This would mean a different semantic major version.
3. Potentially some help information on the commandline when < 3 arguments are provided.

If you're not interested then I'll fork yours and continue development on that fork instead. Please just let me know?

**Comment by enomotodev** [comment]
@axllent I'm not actively developing any more, but PR is welcome!

**Comment by axllent** [comment]
Cool, thanks @enomotodev. I'll be in touch at some stage when I get some time to work on this :+1:
